remote_theme: mmistakes/minimal-mistakes
title: Uselessness
include: ["_pages"]
author:
  name: "all of us"
  avatar: " https://i.pinimg.com/736x/08/a7/f9/08a7f9bc09a451b2c34b6a5647ec1337--roast-me-this-meme.jpg"
  Bio: This is allowed....
